const currencyInfo = {
  code: 'USD',
  symbol: '$',
  template: '$1',
};

const buildVariant = ({ id, title, price, salePrice = null, inventory = 25, imageUrl = null }) => ({
  id,
  title,
  image_url: imageUrl,
  sku: id.toUpperCase(),
  price_in_cents: price * 100,
  sale_price_in_cents: salePrice ? salePrice * 100 : null,
  currency: 'USD',
  currency_info: currencyInfo,
  price_formatted: `$${price.toFixed(2)}`,
  sale_price_formatted: salePrice ? `$${salePrice.toFixed(2)}` : null,
  manage_inventory: true,
  weight: null,
  options: [],
  inventory_quantity: inventory,
});

export const fakeMerchandiseProducts = [
  {
    id: 'fake_summit_hoodie',
    title: 'AAC Summit Hoodie',
    subtitle: 'Heavyweight fleece for cold belays and trailhead mornings.',
    ribbon_text: 'New',
    description: '<p>A soft midweight hoodie with AAC graphics, kangaroo pocket warmth, and a relaxed fit for travel and crag days.</p>',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80',
    price_in_cents: 6800,
    currency: 'USD',
    purchasable: true,
    order: 9001,
    site_product_selection: 'lowest_price_first',
    images: [
      { url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80', order: 0, type: 'image' },
      { url: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=1200&q=80', order: 1, type: 'image' },
    ],
    options: [],
    variants: [buildVariant({ id: 'fake_summit_hoodie_std', title: 'Standard', price: 68, inventory: 18, imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80' })],
    collections: [],
    additional_info: [
      { id: 'fake_summit_hoodie_info', order: 0, title: 'Details', description: '<p>Unisex fit, brushed interior, and durable drawcords for year-round layering.</p>' },
    ],
    type: { value: 'apparel' },
    custom_fields: [],
    related_products: [],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'fake_camp_mug',
    title: 'AAC Camp Mug',
    subtitle: 'Steel mug for coffee at the trailhead or camp.',
    ribbon_text: 'Staff Pick',
    description: '<p>A powder-coated mug sized for early starts, post-climb coffee, and campsite soup.</p>',
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=1200&q=80',
    price_in_cents: 2200,
    currency: 'USD',
    purchasable: true,
    order: 9002,
    site_product_selection: 'lowest_price_first',
    images: [
      { url: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=1200&q=80', order: 0, type: 'image' },
    ],
    options: [],
    variants: [buildVariant({ id: 'fake_camp_mug_std', title: 'Enamel', price: 22, inventory: 42, imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=1200&q=80' })],
    collections: [],
    additional_info: [
      { id: 'fake_camp_mug_info', order: 0, title: 'Details', description: '<p>Lightweight steel construction with a rolled rim and AAC mark.</p>' },
    ],
    type: { value: 'gear' },
    custom_fields: [],
    related_products: [],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'fake_logo_beanie',
    title: 'AAC Logo Beanie',
    subtitle: 'Stretch knit warmth for winter approaches.',
    ribbon_text: 'Winter',
    description: '<p>A low-profile knit beanie that packs small and keeps you warm on cold starts.</p>',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80',
    price_in_cents: 2800,
    currency: 'USD',
    purchasable: true,
    order: 9003,
    site_product_selection: 'lowest_price_first',
    images: [
      { url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80', order: 0, type: 'image' },
    ],
    options: [],
    variants: [buildVariant({ id: 'fake_logo_beanie_std', title: 'One Size', price: 28, inventory: 30, imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80' })],
    collections: [],
    additional_info: [
      { id: 'fake_logo_beanie_info', order: 0, title: 'Details', description: '<p>Soft acrylic knit with a fold cuff and understated AAC patch.</p>' },
    ],
    type: { value: 'apparel' },
    custom_fields: [],
    related_products: [],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'fake_nalgene',
    title: 'AAC Nalgene Bottle',
    subtitle: 'Wide-mouth hydration for long days outside.',
    ribbon_text: 'Trail Ready',
    description: '<p>A one-liter bottle with AAC graphics and a wide-mouth cap that is easy to clean and refill.</p>',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1200&q=80',
    price_in_cents: 1900,
    currency: 'USD',
    purchasable: true,
    order: 9004,
    site_product_selection: 'lowest_price_first',
    images: [
      { url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1200&q=80', order: 0, type: 'image' },
    ],
    options: [],
    variants: [buildVariant({ id: 'fake_nalgene_std', title: '1L Bottle', price: 19, inventory: 35, imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1200&q=80' })],
    collections: [],
    additional_info: [
      { id: 'fake_nalgene_info', order: 0, title: 'Details', description: '<p>BPA-free Tritan bottle made for trail use and daily carry.</p>' },
    ],
    type: { value: 'gear' },
    custom_fields: [],
    related_products: [],
    updated_at: new Date().toISOString(),
  },
];

export const getFakeMerchandiseProducts = () => fakeMerchandiseProducts;

export const getFakeMerchandiseProduct = (id) =>
  fakeMerchandiseProducts.find((product) => product.id === id) || null;
